# Generated by Django 4.1.3 on 2023-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0002_retailsdrinksorder_orderitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsdrinksorder',
            name='orderItems',
            field=models.ManyToManyField(to='RetailsApis.retailsdrinksorderitems'),
        ),
        migrations.AlterField(
            model_name='retailsfoodorder',
            name='orderItems',
            field=models.ManyToManyField(to='RetailsApis.retailsfoodorderitems'),
        ),
    ]
