# Generated by Django 4.1.3 on 2023-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0012_hoteldrinksorder_orderitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldrinksorder',
            name='orderItems',
            field=models.ManyToManyField(to='HotelApis.hoteldrinksorderitems'),
        ),
        migrations.AlterField(
            model_name='hotelroomsorder',
            name='orderItems',
            field=models.ManyToManyField(to='HotelApis.hotelroomsorderitems'),
        ),
    ]
